// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestRamsay.Data;

#nullable disable

namespace TestRamsay.API.Migrations
{
    [DbContext(typeof(TestRamsayDBContext))]
    [Migration("20230424161519_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("TestRamsay.Data.Entities.Degree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Degree");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer Science",
                            Price = 12000000.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Data Modeling",
                            Price = 11000000.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Analytics",
                            Price = 11500000.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Energy & Sustainability",
                            Price = 11500000.0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Innovation",
                            Price = 6500000.0
                        });
                });

            modelBuilder.Entity("TestRamsay.Data.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<int>("DegreeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("GenderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DegreeId");

                    b.HasIndex("GenderId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "4328 Laurel Lane Hobbs, TX 88240",
                            Birthday = new DateOnly(1944, 1, 23),
                            DegreeId = 3,
                            Email = "CodyKShepley@rhyta.com",
                            GenderId = 1,
                            Name = "Cody K. Shepley",
                            Phone = "4322970107",
                            SSN = "463-05-XXXX"
                        },
                        new
                        {
                            Id = 2,
                            Address = "264 Green Acres Road Nashville, NC 27856",
                            Birthday = new DateOnly(1987, 5, 16),
                            DegreeId = 1,
                            Email = "KristopherCLyon@jourrapide.com",
                            GenderId = 1,
                            Name = "Kristopher C. Lyon",
                            Phone = "2524599441",
                            SSN = "681-05-XXXX"
                        },
                        new
                        {
                            Id = 3,
                            Address = "1611 Ersel Street Dallas, TX 75215",
                            Birthday = new DateOnly(1981, 9, 25),
                            DegreeId = 5,
                            Email = "TracyBBridges@teleworm.us",
                            GenderId = 2,
                            Name = "Tracy B. Bridges",
                            Phone = "2144211527",
                            SSN = "457-36-XXXX"
                        },
                        new
                        {
                            Id = 4,
                            Address = "4932 Randolph Street Natick, MA 01760",
                            Birthday = new DateOnly(1999, 1, 5),
                            DegreeId = 2,
                            Email = "StacyEMiller@dayrep.com",
                            GenderId = 2,
                            Name = "Stacy E. Miller",
                            Phone = "508-651-0738",
                            SSN = "019-12-XXXX"
                        });
                });

            modelBuilder.Entity("TestRamsay.Data.Models.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Male"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Female"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("TestRamsay.Data.Entities.Student", b =>
                {
                    b.HasOne("TestRamsay.Data.Entities.Degree", "Degree")
                        .WithMany("Student")
                        .HasForeignKey("DegreeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TestRamsay.Data.Models.Gender", "Gender")
                        .WithMany("Student")
                        .HasForeignKey("GenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Degree");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("TestRamsay.Data.Entities.Degree", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("TestRamsay.Data.Models.Gender", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
